export const COPY = {
  app: {
    title: "LOSM",
    tagline: "Tìm địa điểm và đặt lịch hẹn.",
  },
  nav: {
    today: "Hôm nay",
    sessions: "Hội thoại",
    settings: "Cài đặt",
    logout: "Đăng xuất",
    menu: "Mở menu",
    close: "Đóng",
    profile: "Tài khoản",
  },
  auth: {
    loginTitle: "Đăng nhập",
    registerTitle: "Tạo tài khoản",
    email: "Email",
    password: "Mật khẩu",
    displayName: "Tên hiển thị",
    submitLogin: "Đăng nhập",
    submitRegister: "Đăng ký",
    switchToRegister: "Chưa có tài khoản? Đăng ký",
    switchToLogin: "Đã có tài khoản? Đăng nhập",
    invalidCredentials: "Email hoặc mật khẩu không đúng.",
  },
  search: {
    placeholder: "Tìm quán cà phê, nhà hàng, khách sạn…",
    button: "Tìm",
    tabOne: "Tìm quanh đây",
    tabMany: "Tìm điểm gặp nhiều người",
    addOrigin: "Thêm vị trí",
    removeOrigin: "Bỏ vị trí",
    radius: (km: number) => `Bán kính ${km} km`,
    empty: "Nhập từ khoá và bấm Tìm.",
    noResults: "Không tìm thấy địa điểm phù hợp.",
    resultsFor: (q: string) => `Kết quả cho "${q}"`,
    aiAssistant: "Trợ lý AI",
    aiAssistantHint: "Hỏi AI để tìm nhanh hơn",
  },
  chat: {
    placeholder: "Gõ tin nhắn…",
    send: "Gửi",
    stop: "Dừng",
    empty: "Bắt đầu bằng một câu hỏi — ví dụ: tìm quán cà phê gần đây.",
    thinking: "Đang suy nghĩ…",
    step: {
      toolCall: (toolName: string) => `Đang gọi ${toolName}…`,
      toolResult: (toolName: string) => `Đã nhận kết quả từ ${toolName}.`,
      finalize: "Đang soạn câu trả lời…",
      pendingAction: "Đang chuẩn bị hành động cần xác nhận…",
      fallback: "Đang xử lý…",
    },
    role: {
      user: "Bạn",
      assistant: "Trợ lý",
    },
    bookPrompt: (placeName: string) =>
      `Tôi muốn đặt lịch hẹn tại "${placeName}". Hãy hỏi tôi giờ và email người tham dự.`,
    quickActions: [
      "Tìm quán cà phê gần đây",
      "Tìm nhà hàng Việt Nam",
      "Tìm điểm gặp 3 người",
    ],
  },
  place: {
    distance: (km: number) => `${km.toFixed(1)} km`,
    rating: (score: number) => `★ ${score.toFixed(1)}`,
    book: "Đặt lịch hẹn",
    save: "Lưu",
    saved: "Đã lưu",
    openDetail: "Xem chi tiết",
    noResults: "Không tìm thấy địa điểm phù hợp.",
    detail: {
      dash: "—",
      distanceKm: (km: number) => `${km.toFixed(2)} km`,
      score: (score: number) => `Điểm ${score.toFixed(2)}`,
      sourceOsm: "Nguồn: OpenStreetMap",
      sourceSystem: "Nguồn: Hệ thống",
      savedToast: (placeName: string) =>
        `Đã lưu "${placeName}" vào Đã lưu`,
    },
  },
  meeting: {
    title: "Đặt lịch hẹn",
    fieldTitle: "Tiêu đề cuộc hẹn",
    fieldStart: "Thời gian bắt đầu",
    fieldAttendees: "Email người tham dự",
    fieldNotes: "Ghi chú",
    submit: "Xác nhận",
    retry: "Gửi lại email lỗi",
    confirmTitle: "Anh/chị cho mình xác nhận nhé",
    confirmSubtitle:
      "Hành động này sẽ gửi lời mời tới những người tham dự.",
  },
  sessions: {
    newChat: "Cuộc trò chuyện mới",
    current: "Phiên hiện tại",
    empty: "Chưa có cuộc trò chuyện nào.",
    loading: "Đang tải…",
    loadError: "Không tải được lịch sử.",
    loadMore: "Xem thêm",
  },
  profile: {
    title: "Hồ sơ",
    emailLabel: "Email",
    displayNameLabel: "Tên hiển thị",
    usernameLabel: "Tên đăng nhập",
    memberSinceLabel: "Tham gia từ",
    savedPlacesTitle: "Địa điểm đã lưu",
    savedPlacesEmpty: "Chưa có địa điểm nào.",
    savedPlacesRemove: "Bỏ lưu",
    back: "Về trang chính",
    notLoggedIn: "Vui lòng đăng nhập.",
  },
  errors: {
    generic: "Đã có lỗi xảy ra. Vui lòng thử lại.",
    network: "Mất kết nối mạng.",
    unauthorized: "Phiên đăng nhập đã hết hạn.",
    notFound: "Không tìm thấy.",
  },
} as const;

export type Copy = typeof COPY;
