// <auto-generated />
using System;
using Areas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Areas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AreasDbContext))]
    [Migration("20261008130645_InitialAreas")]
    partial class InitialAreas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Areas.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BboxMaxLat")
                        .HasColumnType("float");

                    b.Property<double>("BboxMaxLng")
                        .HasColumnType("float");

                    b.Property<double>("BboxMinLat")
                        .HasColumnType("float");

                    b.Property<double>("BboxMinLng")
                        .HasColumnType("float");

                    b.Property<string>("ExternalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExternalCode");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("Level", "ParentId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("Areas.Domain.Entities.Area", b =>
                {
                    b.HasOne("Areas.Domain.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
